create table if not exists public.leaderboard_projection(user_id uuid primary key references auth.users(id) on delete cascade,cohort_id uuid references public.cohorts(id),current_streak int not null default 0,best_streak int not null default 0,completion_pct numeric(5,2) not null default 0,completed_days int not null default 0,updated_at timestamptz not null default now());
create table if not exists public.audit_events(id uuid primary key default gen_random_uuid(),actor_id uuid references auth.users(id),event_type text not null,target_id uuid,reason text,metadata jsonb not null default '{}',created_at timestamptz not null default now());
create table if not exists public.push_subscriptions(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users(id) on delete cascade,device_session_id uuid references public.device_sessions(id) on delete cascade,endpoint text not null unique,p256dh text not null,auth text not null,enabled boolean not null default true,last_success_at timestamptz,last_failure_at timestamptz);
create table if not exists public.notification_jobs(id uuid primary key default gen_random_uuid(),idempotency_key text unique not null,user_id uuid references auth.users(id),category text not null,payload jsonb not null default '{}',scheduled_at timestamptz not null,status text not null default 'queued',attempts int not null default 0);
alter table public.leaderboard_projection enable row level security;alter table public.push_subscriptions enable row level security;alter table public.notification_jobs enable row level security;alter table public.audit_events enable row level security;
create policy leaderboard_read on public.leaderboard_projection for select to authenticated using(true);
create policy push_self on public.push_subscriptions for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy notification_self on public.notification_jobs for select to authenticated using(user_id=auth.uid());
create policy audit_admin on public.audit_events for select to authenticated using(public.is_admin());
create policy reports_admin_write on public.reports for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy community_admin_write on public.community_posts for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy cohort_admin_write on public.cohorts for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy team_admin_write on public.teams for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy team_members_admin_write on public.team_members for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy schedule_admin_write on public.schedule_templates for all to authenticated using(public.is_admin()) with check(public.is_admin());
